In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/netflix-shows/netflix_titles.csv


In [2]:
# load data
data = pd.read_csv('/kaggle/input/netflix-shows/netflix_titles.csv')

# print the head to see what we're working with

data.head()

show_id     type                                    title  \
0  81145628    Movie  Norm of the North: King Sized Adventure   
1  80117401    Movie               Jandino: Whatever it Takes   
2  70234439  TV Show                       Transformers Prime   
3  80058654  TV Show         Transformers: Robots in Disguise   
4  80125979    Movie                             #realityhigh   

                   director  \
0  Richard Finn, Tim Maltby   
1                       NaN   
2                       NaN   
3                       NaN   
4          Fernando Lebrija   

                                                cast  \
0  Alan Marriott, Andrew Toth, Brian Dobson, Cole...   
1                                   Jandino Asporaat   
2  Peter Cullen, Sumalee Montano, Frank Welker, J...   
3  Will Friedle, Darren Criss, Constance Zimmer, ...   
4  Nesta Cooper, Kate Walsh, John Michael Higgins...   

                                    country         date_added  release_year  \
0  United States, India, South Korea, China  September 9, 2019          2019   
1                            United Kingdom  September 9, 2016          2016   
2                             United States  September 8, 2018          2013   
3                             United States  September 8, 2018          2016   
4                             United States  September 8, 2017          2017   

     rating  duration                           listed_in  \
0     TV-PG    90 min  Children & Family Movies, Comedies   
1     TV-MA    94 min                     Stand-Up Comedy   
2  TV-Y7-FV  1 Season                            Kids' TV   
3     TV-Y7  1 Season                            Kids' TV   
4     TV-14    99 min                            Comedies   

                                         description  
0  Before planning an awesome wedding for his gra...  
1  Jandino Asporaat riffs on the challenges of ra...  
2  With the help of three human allies, the Autob...  
3  When a prison ship crash unleashes hundreds of...  
4  When nerdy high schooler Dani finally attracts...

In [4]:
# replaces null values with unknown

data = data.replace(np.nan, 'Unknown', regex = True)

data.head()

show_id     type                                    title  \
0  81145628    Movie  Norm of the North: King Sized Adventure   
1  80117401    Movie               Jandino: Whatever it Takes   
2  70234439  TV Show                       Transformers Prime   
3  80058654  TV Show         Transformers: Robots in Disguise   
4  80125979    Movie                             #realityhigh   

                   director  \
0  Richard Finn, Tim Maltby   
1                   Unknown   
2                   Unknown   
3                   Unknown   
4          Fernando Lebrija   

                                                cast  \
0  Alan Marriott, Andrew Toth, Brian Dobson, Cole...   
1                                   Jandino Asporaat   
2  Peter Cullen, Sumalee Montano, Frank Welker, J...   
3  Will Friedle, Darren Criss, Constance Zimmer, ...   
4  Nesta Cooper, Kate Walsh, John Michael Higgins...   

                                    country         date_added  release_year  \
0  United States, India, South Korea, China  September 9, 2019          2019   
1                            United Kingdom  September 9, 2016          2016   
2                             United States  September 8, 2018          2013   
3                             United States  September 8, 2018          2016   
4                             United States  September 8, 2017          2017   

     rating  duration                           listed_in  \
0     TV-PG    90 min  Children & Family Movies, Comedies   
1     TV-MA    94 min                     Stand-Up Comedy   
2  TV-Y7-FV  1 Season                            Kids' TV   
3     TV-Y7  1 Season                            Kids' TV   
4     TV-14    99 min                            Comedies   

                                         description  
0  Before planning an awesome wedding for his gra...  
1  Jandino Asporaat riffs on the challenges of ra...  
2  With the help of three human allies, the Autob...  
3  When a prison ship crash unleashes hundreds of...  
4  When nerdy high schooler Dani finally attracts...

In [13]:
# select columns to use for reccomendations

col = ['type', 'director', 'cast', 'country', 'listed_in', 'title']

In [44]:
# function for using the data to get reccommended. This is a string with the columns we are going to use to base reccomendations off

def important_features(x):
    features = []
    for i in range(0, x.shape[0]):
        features.append(x['cast'][i] + ' ' + x['director'][i] + ' ' + x['listed_in'][i] + ' ' + x['title'][i] + ' ' + x['country'][i] + ' ' + x['type'][i])
        
    return features

In [45]:
data['features'] = important_features(data)

data.head()

show_id     type                                    title  \
0  81145628    Movie  Norm of the North: King Sized Adventure   
1  80117401    Movie               Jandino: Whatever it Takes   
2  70234439  TV Show                       Transformers Prime   
3  80058654  TV Show         Transformers: Robots in Disguise   
4  80125979    Movie                             #realityhigh   

                   director  \
0  Richard Finn, Tim Maltby   
1                   Unknown   
2                   Unknown   
3                   Unknown   
4          Fernando Lebrija   

                                                cast  \
0  Alan Marriott, Andrew Toth, Brian Dobson, Cole...   
1                                   Jandino Asporaat   
2  Peter Cullen, Sumalee Montano, Frank Welker, J...   
3  Will Friedle, Darren Criss, Constance Zimmer, ...   
4  Nesta Cooper, Kate Walsh, John Michael Higgins...   

                                    country         date_added  release_year  \
0  United States, India, South Korea, China  September 9, 2019          2019   
1                            United Kingdom  September 9, 2016          2016   
2                             United States  September 8, 2018          2013   
3                             United States  September 8, 2018          2016   
4                             United States  September 8, 2017          2017   

     rating  duration                           listed_in  \
0     TV-PG    90 min  Children & Family Movies, Comedies   
1     TV-MA    94 min                     Stand-Up Comedy   
2  TV-Y7-FV  1 Season                            Kids' TV   
3     TV-Y7  1 Season                            Kids' TV   
4     TV-14    99 min                            Comedies   

                                         description  \
0  Before planning an awesome wedding for his gra...   
1  Jandino Asporaat riffs on the challenges of ra...   
2  With the help of three human allies, the Autob...   
3  When a prison ship crash unleashes hundreds of...   
4  When nerdy high schooler Dani finally attracts...   

                                            features  
0  Alan Marriott, Andrew Toth, Brian Dobson, Cole...  
1  Jandino Asporaat Unknown Stand-Up Comedy Jandi...  
2  Peter Cullen, Sumalee Montano, Frank Welker, J...  
3  Will Friedle, Darren Criss, Constance Zimmer, ...  
4  Nesta Cooper, Kate Walsh, John Michael Higgins...

In [46]:
# tokenize the collection of text we made with t he features column
from sklearn.feature_extraction.text import CountVectorizer
cm = CountVectorizer().fit_transform(data['features'])

In [48]:
# use cosine similarity to figure out simialrities between each movie row
from sklearn.metrics.pairwise import cosine_similarity

cs = cosine_similarity(cm)
# closer to 1 == really similar
# closer to 0 == not similar at all
print(cs)

[[1.         0.07784989 0.07537784 ... 0.07312724 0.06527912 0.13997313]
 [0.07784989 1.         0.0860663  ... 0.25048972 0.1118034  0.09589266]
 [0.07537784 0.0860663  1.         ... 0.12126781 0.26461887 0.30949223]
 ...
 [0.07312724 0.25048972 0.12126781 ... 1.         0.10502101 0.18015094]
 [0.06527912 0.1118034  0.26461887 ... 0.10502101 1.         0.42884501]
 [0.13997313 0.09589266 0.30949223 ... 0.18015094 0.42884501 1.        ]]


In [79]:
# to test, lets get a random movie/show title

title = 'Naruto Shippuden : Blood Prison'
movie_id = data[data.title == title].index.values.astype(int)[0]
print(movie_id)

381


In [80]:
# create a list for similarity score and sort it
scores = sorted(list(enumerate(cs[movie_id])), key = lambda x:x[1], reverse = True)
scores = scores[1:]

In [81]:
#show the top 5 reccomended movies

for i in range(0, 5):
    title1 = data.iloc[scores[i][0]]['title']
    print(title1)

Naruto Shippuden: The Movie
Naruto Shippuden: The Movie: The Lost Tower
Naruto Shippûden the Movie: Bonds
Naruto Shippûden the Movie: The Will of Fire
Naruto the Movie 2: Legend of the Stone of Gelel
